apiVersion: apps/v1
kind: Deployment
metadata:
  name: vstslinuxbuild
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vstslinuxbuild
  template:
    metadata:
      labels:
        app: vstslinuxbuild
    spec:
      containers:
      - name: vstslinuxbuild
        image: {Container_Image_Details}
        ports:
        - containerPort: 443
        resources:
          requests:
            memory: "500Mi"
            cpu: "1"
          limits:
            memory: "956Mi"
            cpu: "2"
        env:
          - name: VSTS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: azuredevops
                key: AZP_URL
          - name: VSTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevops
                key: AZP_TOKEN
          - name: VSTS_POOL
            valueFrom:
              secretKeyRef:
                name: azuredevops
                key: AZP_POOL
      nodeSelector:
        beta.kubernetes.io/os: linux